2021-02-05 16:47:09,439 INFO    MainThread:9538 [wandb_setup.py:_flush():70] setting env: {}
2021-02-05 16:47:09,439 INFO    MainThread:9538 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-05 16:47:09,439 INFO    MainThread:9538 [wandb_setup.py:_flush():70] setting login settings: {'api_key': '6d802b44b97d25931bacec09c5f1095e6c28fe36'}
2021-02-05 16:47:09,439 INFO    MainThread:9538 [wandb_setup.py:_flush():70] setting login settings: {'api_key': '6d802b44b97d25931bacec09c5f1095e6c28fe36'}
2021-02-05 16:47:09,439 INFO    MainThread:9538 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-05 16:47:09,439 INFO    MainThread:9538 [wandb_init.py:_log_setup():318] Logging user logs to /home/wolf/MyCode/HPC/wandb/run-20210205_164709-14va0yi0/logs/debug.log
2021-02-05 16:47:09,439 INFO    MainThread:9538 [wandb_init.py:_log_setup():319] Logging internal logs to /home/wolf/MyCode/HPC/wandb/run-20210205_164709-14va0yi0/logs/debug-internal.log
2021-02-05 16:47:13,110 INFO    MainThread:9538 [wandb_run.py:_console_start():1399] atexit reg
2021-02-05 16:47:13,116 INFO    MainThread:9538 [wandb_run.py:_redirect():1262] redirect: SettingsConsole.REDIRECT
2021-02-05 16:47:13,117 INFO    MainThread:9538 [wandb_run.py:_redirect():1267] Redirecting console.
2021-02-05 16:47:13,120 INFO    MainThread:9538 [redirect.py:install():213] install start
2021-02-05 16:47:13,122 INFO    MainThread:9538 [redirect.py:install():228] install stop
2021-02-05 16:47:13,122 INFO    MainThread:9538 [redirect.py:install():213] install start
2021-02-05 16:47:13,124 INFO    MainThread:9538 [redirect.py:install():228] install stop
2021-02-05 16:47:13,124 INFO    MainThread:9538 [wandb_run.py:_redirect():1313] Redirects installed.
2021-02-05 16:47:15,170 INFO    MainThread:9538 [wandb_run.py:_atexit_cleanup():1369] got exitcode: 1
2021-02-05 16:47:15,170 INFO    MainThread:9538 [wandb_run.py:_restore():1341] restore
2021-02-05 16:47:15,170 INFO    MainThread:9538 [redirect.py:uninstall():232] uninstall start
2021-02-05 16:47:15,170 INFO    MainThread:9538 [redirect.py:_stop():287] _stop: stdout
2021-02-05 16:47:15,171 INFO    stdout    :9538 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-02-05 16:47:15,171 INFO    stdout    :9538 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-02-05 16:47:15,171 INFO    MainThread:9538 [redirect.py:_stop():293] _stop closed: stdout
2021-02-05 16:47:15,171 INFO    MainThread:9538 [redirect.py:_stop():299] _stop joined: stdout
2021-02-05 16:47:15,171 INFO    MainThread:9538 [redirect.py:_stop():301] _stop rd closed: stdout
2021-02-05 16:47:15,171 INFO    MainThread:9538 [redirect.py:uninstall():236] uninstall done
2021-02-05 16:47:15,171 INFO    MainThread:9538 [redirect.py:uninstall():232] uninstall start
2021-02-05 16:47:15,171 INFO    MainThread:9538 [redirect.py:_stop():287] _stop: stderr
2021-02-05 16:47:15,171 INFO    MainThread:9538 [redirect.py:_stop():293] _stop closed: stderr
2021-02-05 16:47:15,171 INFO    stderr    :9538 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-02-05 16:47:15,172 INFO    stderr    :9538 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-02-05 16:47:15,172 INFO    MainThread:9538 [redirect.py:_stop():299] _stop joined: stderr
2021-02-05 16:47:15,172 INFO    MainThread:9538 [redirect.py:_stop():301] _stop rd closed: stderr
2021-02-05 16:47:15,172 INFO    MainThread:9538 [redirect.py:uninstall():236] uninstall done
2021-02-05 16:47:15,474 INFO    MainThread:9538 [wandb_run.py:_wait_for_finish():1492] got exit ret: file_counts {
  wandb_count: 2
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 6271
  total_bytes: 6271
}

2021-02-05 16:47:17,478 INFO    MainThread:9538 [wandb_run.py:_wait_for_finish():1492] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 8667
  total_bytes: 8667
}

2021-02-05 16:47:18,910 INFO    MainThread:9538 [wandb_run.py:_show_files():1714] logging synced files
2021-02-05 16:47:18,912 INFO    MainThread:9538 [internal.py:handle_exit():156] Internal process exited
