WARNING: $PATH does not agree with $PATH_modshare counter. The following directories' usage counters were adjusted to match. Note that this may mean that module unloading may not work correctly.
 /opt/slurm/bin /sw/arch/Debian10/EB_production/2020/software/CUDAcore/11.0.2/nvvm/bin /hpc/eb/compilerwrappers/linkers /sw/arch/Debian10/EB_production/2020/software/binutils/2.34-GCCcore-9.3.0/bin /sw/arch/Debian10/EB_production/2020/software/CUDAcore/11.0.2 /sw/arch/Debian10/EB_production/2020/software/GCCcore/9.3.0/bin /sw/arch/Debian10/EB_production/2020/software/CUDAcore/11.0.2/bin /opt/slurm/sbin /hpc/eb/compilerwrappers/compilers
2021-02-13 16:25:09.291217: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/Python/3.8.2-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libffi/3.3-GCCcore-9.3.0/lib64:/sw/arch/Debian10/EB_production/2020/software/libffi/3.3-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/GMP/6.2.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/SQLite/3.31.1-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/Tcl/8.6.10-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libreadline/8.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/ncurses/6.2-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/bzip2/1.0.8-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/UCX/1.8.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/hwloc/2.2.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libpciaccess/0.16-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libxml2/2.9.10-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/XZ/5.2.5-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/numactl/2.0.13-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/binutils/2.34-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/zlib/1.2.11-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/GCCcore/9.3.0/lib64:/sw/arch/Debian10/EB_production/2020/software/GCCcore/9.3.0/lib
2021-02-13 16:25:09.291249: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-02-13 16:25:09.291216: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/Python/3.8.2-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libffi/3.3-GCCcore-9.3.0/lib64:/sw/arch/Debian10/EB_production/2020/software/libffi/3.3-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/GMP/6.2.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/SQLite/3.31.1-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/Tcl/8.6.10-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libreadline/8.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/ncurses/6.2-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/bzip2/1.0.8-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/UCX/1.8.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/hwloc/2.2.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libpciaccess/0.16-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libxml2/2.9.10-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/XZ/5.2.5-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/numactl/2.0.13-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/binutils/2.34-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/zlib/1.2.11-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/GCCcore/9.3.0/lib64:/sw/arch/Debian10/EB_production/2020/software/GCCcore/9.3.0/lib
2021-02-13 16:25:09.291217: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/Python/3.8.2-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libffi/3.3-GCCcore-9.3.0/lib64:/sw/arch/Debian10/EB_production/2020/software/libffi/3.3-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/GMP/6.2.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/SQLite/3.31.1-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/Tcl/8.6.10-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libreadline/8.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/ncurses/6.2-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/bzip2/1.0.8-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/UCX/1.8.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/hwloc/2.2.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libpciaccess/0.16-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libxml2/2.9.10-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/XZ/5.2.5-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/numactl/2.0.13-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/binutils/2.34-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/zlib/1.2.11-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/GCCcore/9.3.0/lib64:/sw/arch/Debian10/EB_production/2020/software/GCCcore/9.3.0/lib
2021-02-13 16:25:09.291249: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-02-13 16:25:09.291340: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-02-13 16:25:09.299938: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/Python/3.8.2-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libffi/3.3-GCCcore-9.3.0/lib64:/sw/arch/Debian10/EB_production/2020/software/libffi/3.3-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/GMP/6.2.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/SQLite/3.31.1-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/Tcl/8.6.10-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libreadline/8.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/ncurses/6.2-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/bzip2/1.0.8-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/OpenMPI/4.0.3-GCC-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/UCX/1.8.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/hwloc/2.2.0-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libpciaccess/0.16-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/libxml2/2.9.10-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/XZ/5.2.5-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/numactl/2.0.13-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/binutils/2.34-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/zlib/1.2.11-GCCcore-9.3.0/lib:/sw/arch/Debian10/EB_production/2020/software/GCCcore/9.3.0/lib64:/sw/arch/Debian10/EB_production/2020/software/GCCcore/9.3.0/lib
2021-02-13 16:25:09.300032: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "cifar.py", line 28, in <module>
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, channels)
ValueError: cannot reshape array of size 153600000 into shape (50000,28,28,1)
Traceback (most recent call last):
  File "cifar.py", line 28, in <module>
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, channels)
ValueError: cannot reshape array of size 153600000 into shape (50000,28,28,1)
Traceback (most recent call last):
  File "cifar.py", line 28, in <module>
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, channels)
ValueError: cannot reshape array of size 153600000 into shape (50000,28,28,1)
Traceback (most recent call last):
  File "cifar.py", line 28, in <module>
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, channels)
ValueError: cannot reshape array of size 153600000 into shape (50000,28,28,1)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[39299,1],1]
  Exit code:    1
--------------------------------------------------------------------------

real	0m5.270s
user	0m7.158s
sys	0m1.397s
